name: dartless_web
version: 0.0.1
description: A client web app built using polymer.dart for playing dartbase jeff
author: Brian G. <mixolyde@example.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.1
  polymer: ^1.0.0-rc.2
  reflectable: ^0.3.1
  web_components: ^0.12.0
dev_dependencies:
  test: any

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
