name: dartbase_console_client
version: 0.0.1
description: A command line client for testing Dartbase Jeff
author: Brian G. <mixolyde@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: any
  quiver: any
  redstone: any
  console: any
  gamelogic:
    path: ../dartbase_server

dev_dependencies:
  unittest: any
