name: dartbase_server
version: 0.0.1
description: A server that manages dartbase jeff games
author: Brian G. <mixolyde@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: any
  http: any
  redstone: any
  redstone_web_socket: any
  math: any
dev_dependencies:
  test: '>=0.12.5'
